### ISSUE TITLE
TypeError: Cannot read property 'port' of undefined. After update to version 1.6.11

### ISSUE THREAD

**Issue by dhamanutd** [SadeghHayeri/GreenTunnel#51] opened 2019-12-27 15:16 UTC
**Describe the bug**
Error after update to version 1.6.11

```
/usr/local/lib/node_modules/green-tunnel/bin/gt.js:29
		default: config.port,
		                ^

TypeError: Cannot read property 'port' of undefined
    at Object.<anonymous> (/usr/local/lib/node_modules/green-tunnel/bin/gt.js:29:19)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

**To Reproduce**
1. From green-tunnel 1.4.0 in MacOS Catalina
2. run `npm i -g green-tunnel` to upgrade version to 1.6.11
3. update complete, now run `green-tunnel`
4. Error occurs like above

**Expected behavior**
Running properly as usual

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS Catalina 10.15.2

**Additional context**

**Comment by pcr910303** [comment] 2019-12-27 15:35
Hmm, it's not reproducible: can you give some more context? What version of `node` are you using?
What's the major version number?

**Comment by dhamanutd** [comment] 2019-12-27 15:36
@pcr910303 

node version: v10.16.0
npm version: v6.13.4

**Comment by pcr910303** [comment] 2019-12-27 16:00
Have you tried upgrading? (Didn't test but) looks like the bug is appearing due to the difference of handling module types. At least I don't get any errors on `v13.5.0`.

**Comment by SadeghHayeri** [comment] 2019-12-28 09:52
Maybe the installation will solve your problem.
`npm uninstall -g green-tunnel`

**Comment by phonicfrank** [comment] 2019-12-28 15:19
I'm getting the same error on Mac OS 10.14 Mojave.

Uninstalling & Installing does not fix the issue.

**Comment by SadeghHayeri** [comment] 2019-12-28 18:25
try with ‘—port’ option too. maybe solve the problem.😬
(because of ‘args.port || config.port’)

**Comment by pcr910303** [comment] 2019-12-29 03:33
@dhamanutd Maybe try installing with [`yarn`](https://yarnpkg.com/lang/en/)? I've realized I always used `yarn`, and maybe `npm` is differently resolving dependencies.

Or if you want to get your hands wet and help debugging, you can edit the `GreenTunnel` script and insert a `console.log(require('../src/index.js'));` statement below Line 10 and post the results.
(I suspect you already know but... ) The `gt` script is symlinked to `/usr/local/bin/gt` so you would be able to edit it with `nano /usr/local/bin/gt` or your editor of choice.

@SadeghHayeri I suspect the reason why `config` is `undefined` is that the [`const {Proxy, config, getLogger} = require('../src/index.cjs');`](https://github.com/SadeghHayeri/GreenTunnel/blob/master/bin/gt.js#L10) part is returing some strange value. [Line 29](https://github.com/SadeghHayeri/GreenTunnel/blob/master/bin/gt.js#L29) is the first occurrence of `config`, and `Proxy` might be undefined too. Not sure why (`getLogger`)[https://github.com/SadeghHayeri/GreenTunnel/blob/master/bin/gt.js#L12] does get imported properly?

[`src/index.cjs.js`](https://github.com/SadeghHayeri/GreenTunnel/blob/master/src/index.cjs.js) is implemented by requiring [`src/index.js`](https://github.com/SadeghHayeri/GreenTunnel/blob/master/src/index.js) through the `esm` module.

I'm not sure, but maybe the `esm` module is one of the offenders? AFAIK `node` changed some experimental module support, and the `esm` module can be interacting with that. Converting the whole project to CommonJS might be a solution, but l don't want to do that when `node`'s ESM support is right at the corner.

**Comment by crierr** [comment] 2020-01-04 08:45
I had same problem and it was because of a cache file `esm` module made.
cache file looked like below, which exports old `getConfig` instead of `config`
```
.../lib/node_modules/green-tunnel/node_modules/.cache/esm/e5d042d934e7ddee.js:1:
let net,setProxy,unsetProxy,handleRequest,DNSOverTLS,DNSOverHTTPS,getConfig,getLogger;
```
Cleaning up npm cache would resolve this issue
```
npm cache clean -f
```
or if you're not using node 13+, installing newer version would have same effect
(I had to install node 13+ to use 1.6.11 because of `export` keyword)

**Closed** 2020-01-04 14:34 UTC

**Comment by dhamanutd** [comment] 2020-01-14 17:42
following @pcr910303 suggestion. I tried to fix itself directly to the `/usr/local/bin/gt` file.

just changed some lines
```
const {Proxy, config, getLogger} = require('../src/index.cjs');
```
to
```
const {Proxy, getConfig, getLogger} = require('../src/index.cjs');
const config = getConfig();
```

want to create the pull request for this, but i see the latest code in `master` branch in `index.js` file has already named properly for the `config` variable.

@SadeghHayeri
